import Head from 'next/head';
import '../styles/globals.css';
import Navbar from '../components/navbar';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Guest List</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'></link>
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar /> <Component {...pageProps} />{' '}
    </>
  );
}

export default MyApp;
