import Head from 'next/head';
import styles from '../styles/Home.module.css';
import useSWR from 'swr';

import Navbar from '../components/navbar';
import GuestList from '../components/guestList';


export const fetcher = (url) => fetch(url).then((res) => res.json());

export default function HomePage() {

  const { data, error } = useSWR('/api/guests', fetcher);

  if (error) return 'An error has occurred: ' + error;
  if (!data) return 'Loading...';

  return (
    <div>
      <Head>
        <title>Guest List</title>
        <meta name='description' content='Generated by create next app' />
        <link
          rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'></link>
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Navbar />
        <GuestList data={data} />
      </main>

    </div>

  );
}
