import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

//TODO: fix card's style
export default function HomePage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Guest List</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Guest List</h1>

        <div className={styles.grid}>
          <Link href='/task1' className={styles.card}>
            <a>
              <h2>First Task &rarr;</h2>
            </a>
          </Link>

          <Link
            href='https://nextjs.org/learn'
            className={styles.card}
            className='link'>
            <a>
              <h2>Second Task &rarr;</h2>
            </a>
          </Link>

          <Link
            href='https://github.com/vercel/next.js/tree/master/examples'
            className={styles.card}>
            <a>
              <h2>Third Task &rarr;</h2>
            </a>
          </Link>

          <Link
            href='https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
            className={styles.card}>
            <a>
              <h2>Fourth Task &rarr;</h2>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://www.theknot.com/paper'
          target='_blank'
          rel='noopener noreferrer'>
          Powered by{' '}
          <span className={styles.logo}>
            <Image
              src='/the_Knot_Logo_full.png'
              alt='The Knot Logo'
              width={80}
              height={20}
            />
          </span>
        </a>
      </footer>
    </div>
  );
}
